In [1]:
import gspread
import google 

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import sqlite3
import os

In [ ]:
json_cred_filename = os.getenv("JSON_CREDENTIALS_FILENAME")

gc = gspread.service_account(filename=json_cred_filename)

# Abrindo a planilha pelo nome ou URL
planilha = gc.open("Tá Na Mesa - Pesquisa de Campo")
aba = planilha.sheet1

In [3]:
planilha = aba.get_all_values()
df = pd.DataFrame(planilha)
df = df.rename(columns=df.iloc[0]).drop(df.index[0])

df_columns = list(df.columns)
df_columns[0] = "Submission ID"
df_columns[1] = "Respondent ID"
df_columns[2] = "Submitted at"

df.columns = df_columns

In [4]:
# Remove colunas vazias de verdade: valores em branco, espaços ou totalmente nulos.
df.replace(r'^\s*$', np.nan, regex=True, inplace=True)
df = df.dropna(how="all", axis=1)
df = df.loc[:, df.columns.astype(str).str.strip() != ""]

df['Indice manual'] = range(1, len(df) + 1)

len(df.columns)

C:\Users\carlo\AppData\Local\Temp\ipykernel_27368\1739949467.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace(r'^\s*$', np.nan, regex=True, inplace=True)

46

In [5]:
df = df.drop(columns=[col for col in df.columns if col == ""], errors='ignore')

# Ou, se quiser remover colunas que são "Unnamed" (comum no Pandas)
df = df.loc[:, ~df.columns.str.contains('^Unnamed', na=False)]
df

,Submission ID,Respondent ID,Submitted at,Selecione o seu município,Você é inscrito no programa CadÚnico?,Qual é a sua condição de trabalho atual?,Quantas pessoas moram com você?,"Nos últimos meses, você teve medo da comida da sua casa acabar antes de ter dinheiro para comprar mais?",Qual é a sua renda familiar mensal?,"No restaurante do programa Tá Na Mesa, você recebe apenas a sua refeição?",...,Você já deixou de comer alguma refeição do programa Tá Na Mesa por que não gostou do cardápio do dia?,Em que momento você descobre o cardápio que será servido no dia?,"Quando você não gosta do cardápio do dia, o que você faz com a refeição?",A sua sugestão de mudança do cardápio foi atendida?,"Para uma única pessoa, a quantidade de comida das refeições é suficiente?","A quantidade de carne, frango ou peixe servida nas refeições é suficiente?","Levando em conta todas as refeições que você já recebeu durante o programa Tá Na Mesa, como você avalia o sabor das refeições?","Em relação a todo o programa Tá Na Mesa, qual o seu nível de satisfação?","Na sua opinião, o programa Tá Na Mesa precisa ser continuado?",Indice manual
1,PRDkx7x,MedkPJM,2026-04-17 11:37:52,João Pessoa,"Sim, sou inscrito",Desempregado(a),Moro com 3(três) pessoas ou mais,"Sim, tive medo da comida acabar",Até 1(um) salário mínimo,"Não, recebo a minha refeição e a de mais uma p...",...,"Nunca, pois como a refeição mesmo se não gosta...",Apenas após receber a refeição ou comprar a ficha,Como a refeição mesmo assim,"Não, não foi atendida","Sim, é suficiente pois fico saciado(a) com a q...","Sim, é suficiente pois a quantidade de carne, ...",Bom,Satisfeito,"Sim, precisa ser continuado",1
2,5X4MNVv,Ekbjg1A,2026-04-17 11:44:16,João Pessoa,"Sim, sou inscrito",Desempregado(a),Moro sozinho(a),"Não, não tive medo da comida acabar",Até 1(um) salário mínimo,"Sim, recebo apenas a minha refeição",...,Raramente deixo de comer alguma refeição do pr...,Apenas após receber a refeição ou comprar a ficha,Como a refeição mesmo assim,NaN,"Sim, é suficiente pois fico saciado(a) com a q...","Sim, é suficiente pois a quantidade de carne, ...",Bom,Satisfeito,"Sim, precisa ser continuado",2
3,rDBYy5L,7R9Bz7Z,2026-04-17 12:01:25,Curral de Cima,"Não, não sou inscrito",Desempregado(a),Moro com 2(duas) pessoas,"Não, não tive medo da comida acabar",Até 1(um) salário mínimo,"Não, recebo a minha refeição e a de mais uma p...",...,"Nunca, gosto de todas as refeições do cardápio...",Apenas após receber a refeição ou comprar a ficha,Como a refeição mesmo assim,"Sim, foi atendida","Sim, é suficiente pois fico saciado(a) com a q...","Sim, é suficiente pois a quantidade de carne, ...",Muito bom,Satisfeito,"Sim, precisa ser continuado",3
4,zENd5ZZ,aQjN54v,2026-04-17 13:58:38,Sobrado,"Sim, sou inscrito",Trabalho informalmente,Moro com 3(três) pessoas ou mais,"Sim, tive medo da comida acabar",Até 1(um) salário mínimo,"Sim, recebo apenas a minha refeição",...,"Nunca, gosto de todas as refeições do cardápio...",Antes de chegar no restaurante,Como a refeição mesmo assim,NaN,"Sim, é suficiente pois fico saciado(a) com a q...","Sim, é suficiente pois a quantidade de carne, ...",Muito bom,Muito satisfeito,"Não, não deve ser continuado",4
5,o9D4xrP,9q6WoMp,2026-04-20 13:28:13,João Pessoa,"Sim, sou inscrito",Trabalho informalmente,Moro com 2(duas) pessoas,"Não, não tive medo da comida acabar",Até 1(um) salário mínimo,"Não, recebo a minha refeição e a de mais uma p...",...,"Nunca, gosto de todas as refeições do cardápio...",Antes de comprar a ficha e já no restaurante,Como a refeição mesmo assim,"Não, não foi atendida","Sim, é suficiente pois fico saciado(a) com a q...","Sim, é suficiente pois a quantidade de carne, ...",Bom,Satisfeito,"Sim, precisa ser continuado",5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
301,YjQZaBd,KYWAQQg,2026-05-21 12:41:59,Santa Cruz,"Sim, sou inscrito",Desempregado(a),Moro com 3(três) pessoas ou mais,"Sim, tive medo da comida acabar",Até 1(um) salário mínimo,"Não, recebo a minha refeição e a de mais uma p...",...,"Nunca, gosto de todas as refeições do cardápio...",Apenas após receber a refeição ou comprar a ficha,Como a refeição mesmo assim,NaN,"Sim, é suficiente pois fico saciado(a) com a q...","Sim, é suficiente pois a quantidade de carne, ...",Muito bom,Muito satisfeito,"Sim, precisa ser continuado",301
302,8NKdrek,pbJXBy8,2026-05-21 13:36:13,Mamanguape,"Sim, sou inscrito",Desempregado(a),Moro com 2(duas) pessoas,"Sim, tive medo da comida acabar",Até 1(um) salário mínimo,"Não, recebo a minha refeição e a de mais uma p...",...,Raramente deixo de comer alguma refeição do pr...,Antes de chegar no restaurante,Jogo a refeição fora,"Não, não foi atendida","Não, não é suficiente pois não fico saciado(a)...","Não, não é suficiente pois a quantidade de car...",Muito ruim,Insatisfeito,"Sim, precisa ser continuado",302
303,aO6BVrb,vGJVq2g,2026-05-21 14:35:07,São Bentinho,"Não, não sou inscrito",Desempregado(a),Moro sozinho(a),"Não, não tive medo da comida acabar",Até 1(um) salário mínimo,"Não, recebo a minha refeição e a de mais uma p...",...,Raramente deixo de comer alguma refeição do pr...,Apenas após receber a refeição ou comprar a ficha,Ofereço a refeição para outra pessoa,NaN,"Sim, é suficiente pois fico saciado(a) com a q...","Não, não é suficiente pois a quantidade de car...",Regular,Muito satisfeito,"Sim, precisa ser continuado",303
304,2je4MEe,5Beo8vv,2026-05-21 14:41:17,Sumé,"Sim, sou inscrito",Desempregado(a),Moro com 2(duas) pessoas,"Sim, tive medo da comida acabar",Até 1(um) salário mínimo,"Não, recebo a minha refeição e a de mais uma p...",...,Frequentemente deixo de comer alguma refeição ...,Antes de comprar a ficha e já no restaurante,Ofereço a refeição para outra pessoa,NaN,"Sim, é suficiente pois fico saciado(a) com a q...","Não, não é suficiente pois a quantidade de car...",Bom,Indiferente,"Sim, precisa ser continuado",304
305,7XWDllL,EkZeZgl,2026-05-21 14:48:19,Sumé,"Sim, sou inscrito",Desempregado(a),Moro com 3(três) pessoas ou mais,"Sim, tive medo da comida acabar",Até 1(um) salário mínimo,"Não, recebo a minha refeição e a de mais uma p...",...,Raramente deixo de comer alguma refeição do pr...,Apenas após receber a refeição ou comprar a ficha,Como a refeição mesmo assim,NaN,"Sim, é suficiente pois fico saciado(a) com a q...","Sim, é suficiente pois a quantidade de carne, ...",Regular,Satisfeito,"Sim, precisa ser continuado",305

In [6]:
def get_dia(x):
    return (x - data_primeira_sub).days + 1

def get_semana(x):
    return ((x - data_primeira_sub).days // 7 ) + 1


df['Submitted at'] = pd.to_datetime(df['Submitted at'])


data_primeira_sub = df['Submitted at'].min()

# Criação da coluna Submitted_at_dia
df['Submitted at_dia'] = df['Submitted at'].apply(lambda x : get_dia(x))

# Criação da coluna Submitted_at_semana
df['Submitted at_semana'] = df['Submitted at'].apply(lambda x : get_semana(x))

In [7]:
# Criação do KPI_1 V.A.G.
opcoes_q6 = [
    'Sim, deixei de comer por falta de dinheiro',
    'Sim, frequentemente deixo de fazer alguma refeição por falta de dinheiro'
]

condicao_q5 = df['Nos últimos meses, você teve medo da comida da sua casa acabar antes de ter dinheiro para comprar mais?'] == 'Sim, tive medo da comida acabar'
condicao_q6 = df['Nos últimos meses, você sentiu fome e não comeu por falta de dinheiro?'].isin(opcoes_q6)

df['kpi_vag'] = np.where(condicao_q5 & condicao_q6, 1, 0)

In [8]:
# Criação do KPI_7 Dependência dos beneficiários em relação ao programa

opcoes_q10 = [
    'Faço apenas a refeição servida pelo programa', 'Faço apenas 2(duas) refeições por dia, contando com a refeição servida pelo programa'
]
condicao_q10 = df['Contando com a refeição distribuída pelo programa Tá Na Mesa, quantas refeições você faz por dia?'].isin(opcoes_q10)
condicao_q9 = df['Sem o programa Tá Na Mesa, você continua se alimentando normalmente?'] == 'Não, dependo totalmente da refeição servida pelo programa'


df['kpi_dependencia'] = np.where(condicao_q9 & condicao_q10, 1, 0)

In [9]:
def get_peso(x):
    if x == 'De 4(quatro) à 5(cinco) vezes por semana': return 4.5
    elif x == 'De 2(duas) à 3(três) vezes por semana': return 2.5
    elif x == 'Cerca de 1(uma) vez por semana': return 1
    elif x == 'Quinzenalmente': return 0.5

# preparação do dataframe para cálculo dos KPIs 2 e 3, que, na verdade, ambos são valores numéricos

df['peso_frequencia_semanal'] = df['Com que frequência você consegue receber alguma refeição do programa Tá Na Mesa?'].apply(lambda x : get_peso(x))
df

,Submission ID,Respondent ID,Submitted at,Selecione o seu município,Você é inscrito no programa CadÚnico?,Qual é a sua condição de trabalho atual?,Quantas pessoas moram com você?,"Nos últimos meses, você teve medo da comida da sua casa acabar antes de ter dinheiro para comprar mais?",Qual é a sua renda familiar mensal?,"No restaurante do programa Tá Na Mesa, você recebe apenas a sua refeição?",...,"A quantidade de carne, frango ou peixe servida nas refeições é suficiente?","Levando em conta todas as refeições que você já recebeu durante o programa Tá Na Mesa, como você avalia o sabor das refeições?","Em relação a todo o programa Tá Na Mesa, qual o seu nível de satisfação?","Na sua opinião, o programa Tá Na Mesa precisa ser continuado?",Indice manual,Submitted at_dia,Submitted at_semana,kpi_vag,kpi_dependencia,peso_frequencia_semanal
1,PRDkx7x,MedkPJM,2026-04-17 11:37:52,João Pessoa,"Sim, sou inscrito",Desempregado(a),Moro com 3(três) pessoas ou mais,"Sim, tive medo da comida acabar",Até 1(um) salário mínimo,"Não, recebo a minha refeição e a de mais uma p...",...,"Sim, é suficiente pois a quantidade de carne, ...",Bom,Satisfeito,"Sim, precisa ser continuado",1,1,1,0,0,4.5
2,5X4MNVv,Ekbjg1A,2026-04-17 11:44:16,João Pessoa,"Sim, sou inscrito",Desempregado(a),Moro sozinho(a),"Não, não tive medo da comida acabar",Até 1(um) salário mínimo,"Sim, recebo apenas a minha refeição",...,"Sim, é suficiente pois a quantidade de carne, ...",Bom,Satisfeito,"Sim, precisa ser continuado",2,1,1,0,0,4.5
3,rDBYy5L,7R9Bz7Z,2026-04-17 12:01:25,Curral de Cima,"Não, não sou inscrito",Desempregado(a),Moro com 2(duas) pessoas,"Não, não tive medo da comida acabar",Até 1(um) salário mínimo,"Não, recebo a minha refeição e a de mais uma p...",...,"Sim, é suficiente pois a quantidade de carne, ...",Muito bom,Satisfeito,"Sim, precisa ser continuado",3,1,1,0,0,4.5
4,zENd5ZZ,aQjN54v,2026-04-17 13:58:38,Sobrado,"Sim, sou inscrito",Trabalho informalmente,Moro com 3(três) pessoas ou mais,"Sim, tive medo da comida acabar",Até 1(um) salário mínimo,"Sim, recebo apenas a minha refeição",...,"Sim, é suficiente pois a quantidade de carne, ...",Muito bom,Muito satisfeito,"Não, não deve ser continuado",4,1,1,0,0,4.5
5,o9D4xrP,9q6WoMp,2026-04-20 13:28:13,João Pessoa,"Sim, sou inscrito",Trabalho informalmente,Moro com 2(duas) pessoas,"Não, não tive medo da comida acabar",Até 1(um) salário mínimo,"Não, recebo a minha refeição e a de mais uma p...",...,"Sim, é suficiente pois a quantidade de carne, ...",Bom,Satisfeito,"Sim, precisa ser continuado",5,4,1,0,1,4.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
301,YjQZaBd,KYWAQQg,2026-05-21 12:41:59,Santa Cruz,"Sim, sou inscrito",Desempregado(a),Moro com 3(três) pessoas ou mais,"Sim, tive medo da comida acabar",Até 1(um) salário mínimo,"Não, recebo a minha refeição e a de mais uma p...",...,"Sim, é suficiente pois a quantidade de carne, ...",Muito bom,Muito satisfeito,"Sim, precisa ser continuado",301,35,5,1,0,4.5
302,8NKdrek,pbJXBy8,2026-05-21 13:36:13,Mamanguape,"Sim, sou inscrito",Desempregado(a),Moro com 2(duas) pessoas,"Sim, tive medo da comida acabar",Até 1(um) salário mínimo,"Não, recebo a minha refeição e a de mais uma p...",...,"Não, não é suficiente pois a quantidade de car...",Muito ruim,Insatisfeito,"Sim, precisa ser continuado",302,35,5,0,0,2.5
303,aO6BVrb,vGJVq2g,2026-05-21 14:35:07,São Bentinho,"Não, não sou inscrito",Desempregado(a),Moro sozinho(a),"Não, não tive medo da comida acabar",Até 1(um) salário mínimo,"Não, recebo a minha refeição e a de mais uma p...",...,"Não, não é suficiente pois a quantidade de car...",Regular,Muito satisfeito,"Sim, precisa ser continuado",303,35,5,0,0,4.5
304,2je4MEe,5Beo8vv,2026-05-21 14:41:17,Sumé,"Sim, sou inscrito",Desempregado(a),Moro com 2(duas) pessoas,"Sim, tive medo da comida acabar",Até 1(um) salário mínimo,"Não, recebo a minha refeição e a de mais uma p...",...,"Não, não é suficiente pois a quantidade de car...",Bom,Indiferente,"Sim, precisa ser continuado",304,35,5,0,1,4.5
305,7XWDllL,EkZeZgl,2026-05-21 14:48:19,Sumé,"Sim, sou inscrito",Desempregado(a),Moro com 3(três) pessoas ou mais,"Sim, tive medo da comida acabar",Até 1(um) salário mínimo,"Não, recebo a minha refeição e a de mais uma p...",...,"Sim, é suficiente pois a quantidade de carne, ...",Regular,Satisfeito,"Sim, precisa ser continuado",305,35,5,1,1,4.5

In [10]:
def get_peso_tempo_espera(x):
    if x == "Não preciso esperar, recebo a refeição rapidamente": return 0.25
    elif x == "Espero até 30(trinta) minutos": return 0.5
    elif x == "Espero de 30(trinta) minutos à 1(uma) hora": return 0.75
    elif x == "Espero de 1(uma) hora à 2(duas) horas": return 1.5
    elif x == "Espero por mais de 2(duas) horas": return 2.5


df['peso_tempo_espera'] = df['Quanto tempo você espera na fila para receber a sua refeição?'].apply(lambda x : get_peso_tempo_espera(x))
df['peso_tempo_espera']

1      0.75
2      0.75
3      0.25
4       NaN
5      2.50
       ...
301     NaN
302    0.75
303     NaN
304    0.25
305     NaN
Name: peso_tempo_espera, Length: 305, dtype: float64

In [11]:
# preparação para cálculo dos KPIs 4 e 4.1, que, na verdade, ambos são valores numéricos

df['ja_ficou_sem_receber_refeicao_mesmo_na_fila'] = df['Você já esperou na fila e mesmo assim ficou sem receber a refeição?'].apply(lambda x :
    0 if (x == 'Nunca, sempre que entrei na fila recebi a refeição' or x == 'Nunca, até hoje, sempre que entrei na fila recebi a refeição') else 1)
df

,Submission ID,Respondent ID,Submitted at,Selecione o seu município,Você é inscrito no programa CadÚnico?,Qual é a sua condição de trabalho atual?,Quantas pessoas moram com você?,"Nos últimos meses, você teve medo da comida da sua casa acabar antes de ter dinheiro para comprar mais?",Qual é a sua renda familiar mensal?,"No restaurante do programa Tá Na Mesa, você recebe apenas a sua refeição?",...,"Em relação a todo o programa Tá Na Mesa, qual o seu nível de satisfação?","Na sua opinião, o programa Tá Na Mesa precisa ser continuado?",Indice manual,Submitted at_dia,Submitted at_semana,kpi_vag,kpi_dependencia,peso_frequencia_semanal,peso_tempo_espera,ja_ficou_sem_receber_refeicao_mesmo_na_fila
1,PRDkx7x,MedkPJM,2026-04-17 11:37:52,João Pessoa,"Sim, sou inscrito",Desempregado(a),Moro com 3(três) pessoas ou mais,"Sim, tive medo da comida acabar",Até 1(um) salário mínimo,"Não, recebo a minha refeição e a de mais uma p...",...,Satisfeito,"Sim, precisa ser continuado",1,1,1,0,0,4.5,0.75,0
2,5X4MNVv,Ekbjg1A,2026-04-17 11:44:16,João Pessoa,"Sim, sou inscrito",Desempregado(a),Moro sozinho(a),"Não, não tive medo da comida acabar",Até 1(um) salário mínimo,"Sim, recebo apenas a minha refeição",...,Satisfeito,"Sim, precisa ser continuado",2,1,1,0,0,4.5,0.75,0
3,rDBYy5L,7R9Bz7Z,2026-04-17 12:01:25,Curral de Cima,"Não, não sou inscrito",Desempregado(a),Moro com 2(duas) pessoas,"Não, não tive medo da comida acabar",Até 1(um) salário mínimo,"Não, recebo a minha refeição e a de mais uma p...",...,Satisfeito,"Sim, precisa ser continuado",3,1,1,0,0,4.5,0.25,1
4,zENd5ZZ,aQjN54v,2026-04-17 13:58:38,Sobrado,"Sim, sou inscrito",Trabalho informalmente,Moro com 3(três) pessoas ou mais,"Sim, tive medo da comida acabar",Até 1(um) salário mínimo,"Sim, recebo apenas a minha refeição",...,Muito satisfeito,"Não, não deve ser continuado",4,1,1,0,0,4.5,NaN,1
5,o9D4xrP,9q6WoMp,2026-04-20 13:28:13,João Pessoa,"Sim, sou inscrito",Trabalho informalmente,Moro com 2(duas) pessoas,"Não, não tive medo da comida acabar",Até 1(um) salário mínimo,"Não, recebo a minha refeição e a de mais uma p...",...,Satisfeito,"Sim, precisa ser continuado",5,4,1,0,1,4.5,2.50,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
301,YjQZaBd,KYWAQQg,2026-05-21 12:41:59,Santa Cruz,"Sim, sou inscrito",Desempregado(a),Moro com 3(três) pessoas ou mais,"Sim, tive medo da comida acabar",Até 1(um) salário mínimo,"Não, recebo a minha refeição e a de mais uma p...",...,Muito satisfeito,"Sim, precisa ser continuado",301,35,5,1,0,4.5,NaN,0
302,8NKdrek,pbJXBy8,2026-05-21 13:36:13,Mamanguape,"Sim, sou inscrito",Desempregado(a),Moro com 2(duas) pessoas,"Sim, tive medo da comida acabar",Até 1(um) salário mínimo,"Não, recebo a minha refeição e a de mais uma p...",...,Insatisfeito,"Sim, precisa ser continuado",302,35,5,0,0,2.5,0.75,0
303,aO6BVrb,vGJVq2g,2026-05-21 14:35:07,São Bentinho,"Não, não sou inscrito",Desempregado(a),Moro sozinho(a),"Não, não tive medo da comida acabar",Até 1(um) salário mínimo,"Não, recebo a minha refeição e a de mais uma p...",...,Muito satisfeito,"Sim, precisa ser continuado",303,35,5,0,0,4.5,NaN,0
304,2je4MEe,5Beo8vv,2026-05-21 14:41:17,Sumé,"Sim, sou inscrito",Desempregado(a),Moro com 2(duas) pessoas,"Sim, tive medo da comida acabar",Até 1(um) salário mínimo,"Não, recebo a minha refeição e a de mais uma p...",...,Indiferente,"Sim, precisa ser continuado",304,35,5,0,1,4.5,0.25,1
305,7XWDllL,EkZeZgl,2026-05-21 14:48:19,Sumé,"Sim, sou inscrito",Desempregado(a),Moro com 3(três) pessoas ou mais,"Sim, tive medo da comida acabar",Até 1(um) salário mínimo,"Não, recebo a minha refeição e a de mais uma p...",...,Satisfeito,"Sim, precisa ser continuado",305,35,5,1,1,4.5,NaN,1

In [12]:
df['Total diário de submissões'] = df.groupby('Submitted at_dia')['Submitted at_dia'].transform('count')

totais_diarios = df.groupby('Submitted at_dia')['Total diário de submissões'].first()
total_acumulado = totais_diarios.cumsum()

df['Total acumulado de submissões por dia'] = df['Submitted at_dia'].map(total_acumulado)

df['Média diária de submissões'] = df['Total acumulado de submissões por dia'] // df['Submitted at_dia']
df[['Total diário de submissões', 'Total acumulado de submissões por dia', 'Submitted at_dia', 'Média diária de submissões']]

,Total diário de submissões,Total acumulado de submissões por dia,Submitted at_dia,Média diária de submissões
1,4,4,1,4
2,4,4,1,4
3,4,4,1,4
4,4,4,1,4
5,8,12,4,3
...,...,...,...,...
301,5,305,35,8
302,5,305,35,8
303,5,305,35,8
304,5,305,35,8
305,5,305,35,8

In [13]:
df['Total semanal de submissões'] = df.groupby('Submitted at_semana')['Submitted at_semana'].transform('count')

totais_semanais= df.groupby('Submitted at_semana')['Total semanal de submissões'].first()
total_acumulado = totais_semanais.cumsum()

df['Total acumulado de submissões por semana'] = df['Submitted at_semana'].map(total_acumulado)

df['Média semanal de submissões'] = df['Total acumulado de submissões por semana'] // df['Submitted at_semana']
df[['Total semanal de submissões', 'Total acumulado de submissões por semana', 'Submitted at_semana', 'Média semanal de submissões']]

,Total semanal de submissões,Total acumulado de submissões por semana,Submitted at_semana,Média semanal de submissões
1,194,194,1,194
2,194,194,1,194
3,194,194,1,194
4,194,194,1,194
5,194,194,1,194
...,...,...,...,...
301,11,305,5,61
302,11,305,5,61
303,11,305,5,61
304,11,305,5,61
305,11,305,5,61

In [14]:
df["Total de beneficiários"] = len(df)*1

In [15]:
df.replace("", float("NaN"), inplace=True)
df.dropna(how="all", axis=1, inplace=True)

In [16]:
df[df["Submission ID"] == "jePQQMY"]

,Submission ID,Respondent ID,Submitted at,Selecione o seu município,Você é inscrito no programa CadÚnico?,Qual é a sua condição de trabalho atual?,Quantas pessoas moram com você?,"Nos últimos meses, você teve medo da comida da sua casa acabar antes de ter dinheiro para comprar mais?",Qual é a sua renda familiar mensal?,"No restaurante do programa Tá Na Mesa, você recebe apenas a sua refeição?",...,peso_frequencia_semanal,peso_tempo_espera,ja_ficou_sem_receber_refeicao_mesmo_na_fila,Total diário de submissões,Total acumulado de submissões por dia,Média diária de submissões,Total semanal de submissões,Total acumulado de submissões por semana,Média semanal de submissões,Total de beneficiários
280,jePQQMY,RGvZ4lj,2026-05-07 13:53:16,Areial,"Sim, sou inscrito",Trabalho informalmente,Moro sozinho(a),"Sim, tive medo da comida acabar",Até 1(um) salário mínimo,"Sim, recebo apenas a minha refeição",...,4.5,0.75,0,5,283,13,21,283,94,305

In [17]:
df.columns

Index(['Submission ID', 'Respondent ID', 'Submitted at',
       'Selecione o seu município', 'Você é inscrito no programa CadÚnico?',
       'Qual é a sua condição de trabalho atual?',
       'Quantas pessoas moram com você?',
       'Nos últimos meses, você teve medo da comida da sua casa acabar antes de ter dinheiro para comprar mais?',
       'Qual é a sua renda familiar mensal?',
       'No restaurante do programa Tá Na Mesa, você recebe apenas a sua refeição?',
       'As refeições do programa Tá Na Mesa servem todas as pessoas da sua casa?',
       'Nos últimos meses, você sentiu fome e não comeu por falta de dinheiro?',
       'Contando com a refeição distribuída pelo programa Tá Na Mesa, quantas refeições você faz por dia?',
       'Sem o programa Tá Na Mesa, você continua se alimentando normalmente?',
       'Com que frequência você consegue receber alguma refeição do programa Tá Na Mesa?',
       'Em relação à limpeza do restaurante, qual a sua opinião?',
       'Você sabe quantas refeições o restaurante pode servir todo dia?',
       'O restaurante apresenta que tipo de sujeira?',
       'A pessoa que recebe o seu pagamento também entrega a sua refeição ao mesmo tempo?',
       'O restaurante é identificado como parte do programa Tá Na Mesa?',
       'Você sente dificuldade para chegar ao restaurante?',
       'Você sente que tipo de dificuldade para chegar ao restaurante?',
       'Você mora na zona urbana da cidade ou na zona rural da cidade?',
       'Quanto tempo você espera na fila para receber a sua refeição?',
       'Você sente alguma dificuldade enquanto espera pela sua refeição?',
       'Você já esperou na fila e mesmo assim ficou sem receber a refeição?',
       'Qual o motivo de você não receber refeição alguma mesmo esperando na fila?',
       'Você já recebeu refeições servidas em embalagens danificadas ou sujas?',
       'Você já recebeu refeições servidas sem garfo, faca ou colher?',
       'Você já recebeu sua refeição fria?',
       'Você já sentiu mal-estar causado por alguma refeição do programa Tá Na Mesa?',
       'Você já percebeu alguma refeição estragada?',
       'Porque você acha que a refeição estava estragada?',
       'Você já tentou sugerir alguma mudança ao cardápio do restaurante?',
       'As refeições ofertadas diariamente são variadas?',
       'O restaurante já serviu a mesma refeição 2(duas) ou mais vezes seguidas?',
       'Você já deixou de comer alguma refeição do programa Tá Na Mesa por que não gostou do cardápio do dia?',
       'Em que momento você descobre o cardápio que será servido no dia? ',
       'Quando você não gosta do cardápio do dia, o que você faz com a refeição?',
       'A sua sugestão de mudança do cardápio foi atendida? ',
       'Para uma única pessoa, a quantidade de comida das refeições é suficiente?',
       'A quantidade de carne, frango ou peixe servida nas refeições é suficiente?',
       'Levando em conta todas as refeições que você já recebeu durante o programa Tá Na Mesa, como você avalia o sabor das refeições?',
       'Em relação a todo o programa Tá Na Mesa, qual o seu nível de satisfação?',
       'Na sua opinião, o programa Tá Na Mesa precisa ser continuado? ',
       'Indice manual', 'Submitted at_dia', 'Submitted at_semana', 'kpi_vag',
       'kpi_dependencia', 'peso_frequencia_semanal', 'peso_tempo_espera',
       'ja_ficou_sem_receber_refeicao_mesmo_na_fila',
       'Total diário de submissões', 'Total acumulado de submissões por dia',
       'Média diária de submissões', 'Total semanal de submissões',
       'Total acumulado de submissões por semana',
       'Média semanal de submissões', 'Total de beneficiários'],
      dtype='object')

In [18]:
len(df.columns)

60

In [ ]:
import pandas as pd
import sqlite3
from sqlalchemy import create_engine
import os

string_conexao = os.getenv("RETOOL_CREDENTIALS")
engine_postgres = create_engine(string_conexao)

# 5. Enviar o DataFrame inteiro para o PostgreSQL
print("Enviando dados para o PostgreSQL no Retool...")

# O parâmetro if_exists='replace' cria a tabela do zero ou substitui a existente.
# Você também pode usar 'append' para apenas adicionar novas linhas.
df.to_sql(
    name='main', 
    con=engine_postgres, 
    if_exists='replace', 
    index=False
)

Enviando dados para o PostgreSQL no Retool...

305

In [20]:
#db_path = "./db/test_db.sqlite"
#conn = sqlite3.connect(db_path)

#df.to_sql('main', conn, if_exists='replace', index=False)

#conn.close()